name: 'Render-R-markdown'
description: 'Render R markdown file(s)'

runs:
  using: "composite"
  steps:
    - uses: r-lib/actions/setup-pandoc@v2
    - uses: r-lib/actions/setup-r@v2
    - uses: r-lib/actions/setup-renv@v2

    - name: Render R markdown file(s) and commit results
      run: |
        RMD_PATH=($(git diff --name-only ${{ github.event.before }} ${{ github.sha }} | grep '[.]Rmd$'))
        Rscript -e 'for (f in commandArgs(TRUE)) if (file.exists(f)) rmarkdown::render(f)' ${RMD_PATH[*]}
        git config --local user.name "$GITHUB_ACTOR"
        git config --local user.email "$GITHUB_ACTOR@users.noreply.github.com"
        git commit ${RMD_PATH[*]/.Rmd/.md} -m 'Re-build Rmarkdown files' || echo "No changes to commit"
        git push origin || echo "No changes to commit"
      shell: bash
